### ISSUE TITLE
Detect PHONE_NUMBER

### ISSUE THREAD

**Issue by TiSuaBeh** [NCATComp410/comp410_summer_2024#10]
A phone number is considered to be an important identifier that must be protected by a PII due to not only serving as a way to communicate directly with someone. Phone numbers allow people to determine the location and identity of the person identified through their number. Even though phone numbers across the globe are unique from one another, there are situations where they can be recycled and used by someone else once unclaimed by the number's previous user. Phone numbers can be considered an indirect way of identifying an individual since it isn't a permanent form of identification compared to a social security number. Phone numbers can be used as leverage for scammers to fish information and or promote scams that can jeopardize sensitive information from any of their targets.

Source: 
[Google AI](https://support.google.com/websearch/answer/14901683?hl=en&visit_id=638538137734319206-2434991030&p=ai_overviews&rd=1)
[Cloudflare](https://www.cloudflare.com/learning/privacy/what-is-pii/)

**Comment by ZionPacker** [comment]
How will you detect the different patterns in phone numbers such as dashes or dots?

**Comment by JaKhari2** [comment]
Would you need to start out with an area code before putting the phone number?

**Comment by TiSuaBeh** [comment]
> How will you detect the different patterns in phone numbers such as dashes or dots?

Since these are special characters, I will attempt to account for the number of digits present and have those special characters ensure that a phone number is accounted for specifically.

**Comment by TiSuaBeh** [comment]
> Would you need to start out with an area code before putting the phone number?

I will highlight the area code at the beginning of the phone number with priority because phone numbers can be the same after the area code which will distinguish different identities.
