### ISSUE TITLE
Detect IP_ADDRESS

### ISSUE THREAD

**Issue by shymik01** [NCATComp410/comp410_summer_2024#11]
IP address detection is important for several reasons, most of which have to do with data analytics, network administration, and security. Devices linked to a network are identified uniquely by their IP addresses, which enables internet-based communication between them. Organizations use a variety of security measures, including firewalls, virtual private networks (VPNs), intrusion detection systems (IDS), intrusion prevention systems (IPS), and encryption protocols, to safeguard IP addresses and the related network infrastructure. Furthermore, to maintain a strong security posture and protect sensitive data, regular security audits, software updates, and personnel training are crucial.

For more info on IP address detection click[ here ](https://www.gdpreu.org/the-regulation/key-concepts/personal-data/)

**Comment by emaniem** [comment]
In what way will you identify the structure of the IP address as it relates to length, numbers only, and decimal points in between each number?

**Comment by Jazgreen03** [comment]
What other strategies could organization use to effectively manage and protect IP addresses and the related network setup against potential security threats?

**Comment by shymik01** [comment]
> In what way will you identify the structure of the IP address as it relates to length, numbers only, and decimal points in between each number?

I  will use the representation of an IPv4 address which is a 32-bit value that is split into four decimal places (0–255) and separated by periods. Dotted-decimal notation is a standard that makes devices on a network individually identifiable and makes communication easier between them. The 8-bit binary form of the address is reflected in each segment, or octet, which spans from 0 to 255.
