### ISSUE TITLE
Detect Australian_Business_Numbers 

### ISSUE THREAD

**Issue by ZionPacker** [NCATComp410/comp410_summer_2024#12]
An Australian Business Number is a unique 11-digit identifier issued by the Australian Business Register to Australian businesses. It serves an extremely vital role in business communications as it is used in every deal between companies and agencies, and it is also necessary for businesses to use the number when claiming government benefits. Even more importantly, however, the number is used for business identification ensuring the proper business is being sent documents or money, and for filing taxes with the Australian government. If a business number is kept unguarded then fraudulent activity such as identity theft and misrepresentation of business records may occur, and such activity usually brings great scrutiny and potential legal and financial problems. Thus many companies perform regular audits and updates on their ABN data and details and utilize verification tools to verify the status and accuracy of an ABN before engaging in business activity.

**Comment by brendaar1991** [comment]
How can businesses keep their Australian Business Number (ABN) safe from fraud?
