### ISSUE TITLE
Detect Personal Data

### ISSUE THREAD

**Issue by nbdewitt** [NCATComp410/comp410_summer_2024#14]
Personally Identifiable Information (PII) related to a person typically includes any data that can be used to identify an individual uniquely. Common types of PII include a person’s full name, Social Security Number (SSN), driver's license number, and passport number. Contact details such as email addresses, phone numbers, and physical addresses also fall under PII. Additional identifiers include a person’s date and place of birth, biometric data like fingerprints and facial recognition data, as well as medical information and insurance details. Financial information such as credit card numbers and bank account numbers are also considered PII, along with employment details like employee ID numbers and work history.

Moreover, educational records, including student ID numbers and transcripts, constitute PII. In the digital realm, online identifiers like IP addresses and login credentials are also classified as PII. These pieces of information, whether used individually or in combination, enable the identification, contact, or location of a person. Protecting PII is crucial to safeguarding an individual's privacy and preventing identity theft, fraud, and other forms of misuse.

See [here](https://gdpr-info.eu/issues/personal-data/) for more information about personal data protection.

**Comment by SaintBaroque** [comment]
In the case of fraud, how will you go about making sure the PII being used is actually the current user's information?

**Comment by nbdewitt** [comment]
> In the case of fraud, how will you go about making sure the PII being used is actually the current user's information?

To ensure that PII belongs to the current user in cases of fraud, implementing multi-factor authentication (MFA) is crucial. MFA requires users to verify their identity through multiple methods such as SMS codes, authentication apps, or biometric verification. Additionally, knowledge-based verification, like asking security questions only the true user would know, and document verification using government-issued IDs, are effective strategies.

Behavioral analysis and transaction history analysis help detect unusual activities, while contact verification through registered email or phone numbers adds another layer of security. Cross-referencing PII with third-party databases and using IP address and device fingerprinting can further confirm user identity. Regular audits and updates of security processes ensure they remain effective against evolving fraud techniques. By combining these methods, the authenticity of the PII can be more reliably verified.

**Comment by claesmk** [comment]
@nbdewitt you should wait for the pull request to complete before closing the issue.  GitHub will automatically close the issue for you as you can see in the auto-generated linked pull request comment above
