### ISSUE TITLE
DETECT DATE_TIME

### ISSUE THREAD

**Issue by JaKhari2** [NCATComp410/comp410_summer_2024#16]
Considering that time runs the world, date & time are essentially important when noting types of Personally Identifiable Information (PII). Timestamps associate with dates and events which can show information about specific transactions or events going on. Other data, like preferences or recommendations associated with time and dates can potentially lead to the identification of many resources. Date and Time gives context to the setting of many things like birth, scheduling your day, keeping timelines of existence, and other situations in everyday life. While using other PII's as well as Date Time, you can provide context and identify people easier by having tracked records authorized as well as timestamps using Date Time to help locate things like people, addresses, and events while ensuring security through the PII's. Detecting date and time can link multiple sources of data together and if certain data is very secretive, could be held as time sensitive data which would bring in other types of PII's to work together for a solution. As Date Time plays as one aspect of Personally Identifiable Information, it is vital to maintain security of this to ensure security, keep risk low for data disturbance, as well as keep all information safe. 

Click [here](https://docs.python.org/3/library/datetime.html) for more information on Date Time.

Click [here](https://www.techtarget.com/searchsecurity/definition/personally-identifiable-information-PII) for more information on Personal Identifiable Information.

**Comment by TiSuaBeh** [comment]
Since the date and time around the world can be recorded in (mm/dd/yyyy) or (dd/mm/yyyy), how will you verify that the recorded date is accurate to the time it's attempting to reference?
