### ISSUE TITLE
Detect UK_NHS 

### ISSUE THREAD

**Issue by mljones5** [NCATComp410/comp410_summer_2024#20]
The NHS is the United Kingdom’s National Health Service. It is the UK’s government-funded public health service. The system covers the entire population, making all health services free except for certain minor charges.
Click [here](https://www.nhs.uk/) to learn more about the NHS.
Every patient of the NHS is assigned a 10-digit number, either at birth or at the first time the patient seeks care from the system. This number is a form of Personally Identifiable Information (PII) because it is used by healthcare professionals to match a patient to their health record. These numbers are stored within the Personal Demographics Service (PDS). This database stores medical information along with patient names, addresses, dates of birth, and other medical information. This means that someone with malicious intent could gain access to all of this other information if they were to acquire someone else’s NHS number.
The number is typically(in England) displayed in the format of xxx xxx xxxx but can also be accepted without the spaces. 
Although they are a part of the UK, Scotland and Northern Ireland use different NHS numbering systems.

**Comment by brendaar1991** [comment]
How is the NHS number protected to ensure patient privacy and security?

**Comment by mljones5** [comment]
> How is the NHS number protected to ensure patient privacy and security?

The NHS states that data that is used beyond personal care that can identify a patient is anonymized or pseudonymized. Caldicott Guardians and Data protection officers are also put into place to monitor the handling and safekeeping of confidential patient information.
