### ISSUE TITLE
Detect US_SSN

### ISSUE THREAD

**Issue by claesmk** [NCATComp410/comp410_summer_2024#3]
A U.S. Social Security Number (SSN) is considered highly sensitive and must be protected as Personally Identifiable Information (PII) because it serves as a unique identifier for individuals within the United States for various official purposes, including taxation, employment, and access to government services. Its uniqueness and widespread use across different sectors make it a critical piece of information that, if compromised, can lead to identity theft and fraudulent activities. Malicious actors can use an individual's SSN to open new accounts, obtain credit, and commit crimes in the individual's name, leading to significant financial and legal complications for the victim. Furthermore, the difficulty in changing an SSN means that once it is compromised, it can have long-lasting effects on an individual's privacy and security. Therefore, safeguarding SSNs is essential to prevent unauthorized access and misuse, and to protect individuals' identities and personal information.

See [here](https://www.ssa.gov/policy/docs/ssb/v69n2/v69n2p55.html) for more information about US_SSN

**Comment by mkc2mkc** [comment]
Will you detect SSN format xxx-xx-xxxx or will xxxxxxxxx also be detected?

**Comment by claesmk** [comment]
> Will you detect SSN format xxx-xx-xxxx or will xxxxxxxxx also be detected?

Yes, I will detect both formats
