### ISSUE TITLE
Detecting AU_MEDICARE through Patterns, Context, and Checksum

### ISSUE THREAD

**Issue by emsmdm** [NCATComp410/comp410_summer_2024#4]
An Australian Medicare number is a type of Personal Identification Information (PII) used in the Australian Medicare system. With this number, you can identify if someone has opted into the system, gain access to other insurance plans, and ensure Medicare pays first on the bill. Without this number, one would lose access to their insurance and have to pay medical bills entirely with their own money. If someone steals the number, they can rack up charges with insurance providers under someone else's name. If someone's medicare number is breached, it puts their insurance and savings at risk, making it very important to keep protected.

**Comment by cmokoro** [comment]
Is there any authentication barriers for this PII?

**Comment by emsmdm** [comment]
Yes, there will be multifactor authentication.
