### ISSUE TITLE
Detect CRYPTO

### ISSUE THREAD

**Issue by cmokoro** [NCATComp410/comp410_summer_2024#7]
A cryptographic key is considered very highly sensitive and must be protected as PII because it is fundamental to securing digital data and communication . Cryptographic keys are used in numerous encryption algorithms to protect sensitive information, authenticate users, and ensure data integrity. If a cryptographic key is compromised, malicious unauthorized users can impersonate authorized users and can decrypt confidential information, impersonate legitimate users, and manipulate data, leading to severe data security breaches. The malicous use of cryptographic keys can result in unauthorized access to secure systems, financial losses, and a loss of trust in the security mechanisms of the affected organization. Given the critical role that cryptographic keys play in maintaining the confidentiality, integrity, and authenticity of information, their protection is paramount to preventing unauthorized access and safeguarding sensitive data. Therefore, stringent measures must be taken to secure cryptographic keys and prevent their exposure to unauthorized parties.

For more information about cryptographic keys see [here](https://csrc.nist.gov/publications/detail/sp/800-57-part-1/rev-5/final)

**Comment by JalensMindset** [comment]
What are some ways the average person can secure their cryptographic key?
