### ISSUE TITLE
Detecting US_BANK_NUMBER with Pattern match and context

### ISSUE THREAD

**Issue by JalensMindset** [NCATComp410/comp410_summer_2024#8]
One of the important personally identifiable information (PII) is your bank number. A bank account is your own personal account through a bank that will have your protected banking information. Your bank number is how you will identify your account. There are a lot of benefits to having a bank account. Once you open a checking account in your bank account, you will have a debit card for instant transactions and online pay without having to use cash. You can also open a savings account to save the money you wish to keep for the future and your bank can offer interest rates so you can earn more money the longer you save. With all this being said, it is essential to keep this particular PII secured. Attackers can get your bank number through phishing attacks, malware attacks, skimming devices, and more. So in, order to protect this PII, you're going to want to make sure your passwords are secured, secure your account with biometrics such as face ID and fingerprint, and not falling for scam emails. 

References/More information:
[here](https://www.pnc.com/insights/personal-finance/protect/how-to-protect-bank-account.html#:~:text=Taking%20proactive%20steps%20to%20safeguard,stay%20informed%20about%20key%20threats.)
[here](https://consumer.westchestergov.com/money-management/benefits-of-a-bank-account#:~:text=Bank%20accounts%20are%20cheaper&text=Paying%20bills%3A%20Without%20a%20bank,online%20at%20a%20low%20cost.)

**Comment by Twintastic** [comment]
Will you include the physical and virtual measures that banks have in order to keep their clients bank numbers secure?

**Comment by JalensMindset** [comment]
> Will you include the physical and virtual measures that banks have in order to keep their clients bank numbers secure?

Yes, I intend to use and improve the measures banks use to secure their client's bank numbers.
