### ISSUE TITLE
Detect URL through Parameter Checking and Patterns

### ISSUE THREAD

**Issue by SaintBaroque** [NCATComp410/comp410_summer_2024#9]
With PII's there are many different types of identifiable information that can refer to a person, one being the URL. URL's can disclose things like file names, IP addresses, and possibly even login information for a website if the developer set it up to display this. However, it is important to use these as they provide access to user specific information, and allow for websites to make query's in order to hone in on a specific request. It's important to protect these as they are not only integral to many different systems, but they are also very personal to a user. 
[Source](https://support.google.com/google-ads/answer/6389382?hl=en)

**Comment by Rahjion** [comment]
What are some risks to consider in the event that a URL is not properly protected?

**Comment by SaintBaroque** [comment]
> What are some risks to consider in the event that a URL is not properly protected?

In the event that a URL is not properly protected, hackers or unverified users can get into personal data and access things like accounts, profiles or more using a variety of different techniques like injection.
